---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oreilly-api
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: oreilly-api
        image: tfvoncan/oreilly-repo
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
...

---
apiVersion: v1
kind: Service
metadata:
  name: oreilly-api
  labels:
    app: api
spec:
  ports:
  - port: 8000
    protocol: TCP
  selector:
    app: api

apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: oreilly-api
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: api
  sessionAffinity: None
  type: ClusterIP

...

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: oreilly-nodeport
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32401
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: api
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
...

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: redis
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: db
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
...
