---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oreilly-api
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: oreilly-api
        image: tfvoncan/oreilly-repo
        ports:
        - containerPort: 8000
...

---
apiVersion: v1
kind: Service
metadata:
  name: oreilly-api
  labels:
    app: api
spec:
  ports:
  - port: 8000
    protocol: TCP
  selector:
    app: api
...

---
apiVersion: v1
kind: Service
metadata:
  name: api-node
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - port: 8000
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
...

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: db
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    app: db
...
